# Generated by Django 3.2.8 on 2021-10-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='marc',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='modelo',
        ),
    ]
