# Generated by Django 3.2.8 on 2021-10-22 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211020_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('valor_total', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetaCompra_Prodcut', to='authApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DetaCompra_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
